export const IPC_EVENT_CHANNEL_NAME = {
  ADD_BARRAGE_TO_BARRAGE_WINDOW: "ADD_BARRAGE_TO_BARRAGE_WINDOW",
  BARRAGE_WINDOW_COMPLETE_EVENT_HANDLE: "BARRAGE_WINDOW_COMPLETE_EVENT_HANDLE",
};

export const MAIN_THREAD_FORWARD_EVENT = {
  ADD_BARRAGE: "ADD_BARRAGE",
  COMPLETE_BARRAGE_ADD: "COMPLETE_BARRAGE_ADD",
};
